### ISSUE TITLE
Time for a release! \o/

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/python-keylime#20]
Hi @THS-on, @cpaelzer, @mirespace,

We've done quite a lot of work for 6.1.1 and I think it's time for a release. Unless you tell me otherwise, I plan to prep a new release tomorrow. Let me know if you have questions, concerns, or suggestions. Thank you for all your work! \o/

**Comment by utkarsh2102** [comment]
...and then I expect things to be a bit settled here. We've had a lot of activity going around the splitting bit, hah.

**Comment by cpaelzer** [comment]
Not much of a discussion here, time for a release it is.
To find more issues we'd want it to be used - and that requires a release.

+1
