### ISSUE TITLE
Drop tpm2-abrmd as a dependency

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/python-keylime#24]
From Slack:

> tpm2_abrmd is a dependency of the keylime package — and it ought not to be. We are explicitly not using the abrmd driver; we are using the /dev/tpmrm0 device, which does not need it.

So check back, if we really need this, otherwise drop this before 6.2.0 release.

**Comment by THS-on** [comment]
I've tested it with tpm2-abrmd removed and it works, so we can drop it as a dependency.
