### ISSUE TITLE
Move sqlalchemy and alembic to -server only

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/python-keylime#25]
From Slack:

> sqlalchemy and alembic are dependencies on the keylime package. This was because this package also provided registrar and verifier, whereas in the *** cloud they never do; they only install keylime as a package into the places where it runs as an agent.

And now that've we done the splitting for agent and the server, it's easy for us to move this in the right place. We should do this prior to the 6.2.0 release.

**Comment by mirespace** [comment]
IIUC the target of this PR, If we don't care about what agents needs, because it needs the -lib package:

```
root@bionic-keylime:~/Code/Builds# apt depends python3-keylime-agent
python3-keylime-agent
  Depends: adduser
  Depends: python3
  Depends: python3-keylime-lib
  Depends: <python3:any>
    python3
  Recommends: python3-keylime-doc
  Suggests: python3-keylime-defaultconf
```
I suppose we can remove them from there. If not, the lib package would need to be split (one for server, one for agent, I guess...).
