### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/python-keylime#6]
Hey,

Whilst installing the master branch in Ubuntu Bionic (18.04), I found this error:
`Jul 22 21:50:12 tpm2 keylime_registrar[690]: ModuleNotFoundError: No module named 'dataclasses'`
...and this makes me a bit skeptical as to what's happening. I understand dataclasses is already in-build in Python 3.7+ but we have Python 3.6.9 in Ubuntu Bionic.

Going forward, we have two ways to deal with this:
- Either we package the `dataclasses` module separately, or
- Embed the `dataclasses` module for now until we support Bionic and remove Focal onward.

Weighing the pros and cons of the two options, I feel, it's better to just embed the `dataclasses` module for now as having a separate package will cause upgrade problems which will need to be dealt with `Breaks+Replaces` and what not. And I don't wanna go there. At all.

**Comment by THS-on** [comment]
I'm currently testing your new changes on Debian 11 which has Python 3.9 and the temporarily included dataclasses breaks there. I would propose to load the included `dataclasses` package conditionally only when the system version is less than 3.7.
```
import sys
if sys.version_info >= (3,7):
    import dataclasses
else:
    import keylime.dataclasses as dataclasses
```

**Comment by utkarsh2102** [comment]
Hi @THS-on,

> I'm currently testing your new changes on Debian 11 which has Python 3.9 and the temporarily included dataclasses breaks there. I would propose to load the included `dataclasses` package conditionally only when the system version is less than 3.7.
> 
> ```
> import sys
> if sys.version_info >= (3,7):
>     import dataclasses
> else:
>     import keylime.dataclasses as dataclasses
> ```

Oooh, that is a good! Can you make a PR, please? I'll be happy to merge this right away! 😄
