### ISSUE TITLE
[Errno 13] Permission denied: '/var/lib/keylime/secure/tmp4tejkgp9'

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/python-keylime#7]
Hey,

So once we have #6 fixed, we have this another obstacle before we can release the 6.1.1 version. Even though we have the following lines in the postinst:

https://github.com/utkarsh2102/python-keylime/blob/b91d7e07d221e2cdd6c48a8ba81532bae3aae5e0/debian/python3-keylime.postinst#L28-L31

The `/var/lib/keylime/secure/tmp*` directory still doesn't have the right set of permissions. Ugh. On further investigating and taking hints from Andreas, I understood that this is because `/var/lib/keylime/secure` is a mount point:

https://github.com/utkarsh2102/python-keylime/blob/b91d7e07d221e2cdd6c48a8ba81532bae3aae5e0/debian/python3-keylime.var-lib-keylime-secure.mount#L4-L8

This means that the general `chown` commands don't work via the postinst and needs further investigation as to how to give this the right permission (that is, `chown -R keylime:tss /var/lib/keylime/secure`). Maybe via the mount unit options (like we add `Group` and `User` in service files) or another plausible suggestion put forth by Andreas was using "capabilities". I am not sure how to fix this at the moment and so I am documenting the whole situation here so that other people can chime on this until this issue has my full attention. I am much more concerned on getting #6 fixed atm and completing other things on my plate.

So if you've any ideas, please let me know. Thank you!
(PRs are even more appreciated. Just saying. 😉)

**Comment by utkarsh2102** [comment]
Hah, another funny thing I forgot to mention:

Apparently changing the `mode` in the mount file makes everything work; like this:
```
--- a/debian/python3-keylime.var-lib-keylime-secure.mount
+++ b/debian/python3-keylime.var-lib-keylime-secure.mount
@@ -5,7 +5,7 @@ Description=Keylime configuration filesystem
 What=tmpfs
 Where=/var/lib/keylime/secure
 Type=tmpfs
-Options=mode=0700,size=1m
+Options=mode=0777,size=1m
 
 [Install]
 WantedBy=multi-user.target
```

But of course, having `777` is a bit too much, maybe :P

**Comment by mirespace** [comment]
Hi,

what about adding gid and uid to mount options? I did it and:

![image](https://user-images.githubusercontent.com/35487509/128879712-50ee1ef9-5bd4-4ef9-a435-f2c71ab9fbb4.png)

**Comment by utkarsh2102** [comment]
Woooooohoooooooooo, that is awesome! I think this is what we neeeed! I am so happpy! \o/
